### ISSUE TITLE
Flutter 3.29.0 : Unresolved reference: Registrar

### ISSUE THREAD

**Issue by carpentierchloe** [aakashkondhalkar/external_path#15]
I am having this error since updating Flutter to 3.29.0 : 

../.pub-cache/hosted/pub.dev/external_path-2.0.1/android/src/main/kotlin/com/pinciat/external_path/ExternalPathPlugin.kt:13:48 Unresolved reference: Registrar

Execution failed for task ':external_path:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

Found this note : https://benamorn.medium.com/today-i-learned-after-upgrading-to-flutter-3-29-0-7c7ab1a97975

**Comment by ahmedelkhyary** [comment]
any update

**Comment by mustafaG9** [comment]
solved here 

```
  external_path:
    git:
      url: https://github.com/mustafaG9/external_path.git
      ref: main

```

till the package owner do the PR marge

**Comment by aakashkondhalkar** [comment]
This is now available in version 2.2.0
